--======================================================
-- 20250724 과제2 미니프로젝트 포켓몬
--======================================================
COMMIT;

-- DROP TABLE
DROP TABLE POKEMON_SPECIES CASCADE CONSTRAINTS;
DROP TABLE POKEMON_TRAINER CASCADE CONSTRAINTS;
DROP TABLE POKEMON CASCADE CONSTRAINTS;

-- DROP SEQUENCE
DROP SEQUENCE SEQ_POKEMON_SPECIES;
DROP SEQUENCE SEQ_POKEMON_TRAINER;
DROP SEQUENCE SEQ_POKEMON;

-- CREATE SEQUENCE
CREATE SEQUENCE SEQ_POKEMON_SPECIES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POKEMON_TRAINER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POKEMON START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 1. 포켓몬 종 테이블
CREATE TABLE POKEMON_SPECIES (
    SPECIES_ID      NUMBER          PRIMARY KEY
    , NAME          VARCHAR2(50)    NOT NULL
    , TYPE          VARCHAR2(30)    NOT NULL
)
;

-- 2. 트레이너 테이블
CREATE TABLE POKEMON_TRAINER (
    TRAINER_ID      NUMBER          PRIMARY KEY
    , TRAINER_NAME  VARCHAR2(50)    NOT NULL
)
;

-- 3. 포켓몬 개체 테이블 (종 + 소유자 연결)
CREATE TABLE POKEMON (
    POKEMON_ID      NUMBER          PRIMARY KEY
    , NICKNAME      VARCHAR2(50)
    , POKEMON_LEVEL NUMBER          DEFAULT 1
    , SPECIES_ID    NUMBER          NOT NULL
    , TRAINER_ID    NUMBER          NOT NULL
    , CAUGHT_AT     DATE            DEFAULT SYSDATE
    , MODIFIED_AT   DATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N')) 
)
;

-- FK KEY
ALTER TABLE POKEMON
ADD CONSTRAINT FK_POKEMON_SPECIES
FOREIGN KEY (SPECIES_ID)
REFERENCES POKEMON_SPECIES (SPECIES_ID);

ALTER TABLE POKEMON
ADD CONSTRAINT FK_POKEMON_TRAINER
FOREIGN KEY (TRAINER_ID)
REFERENCES POKEMON_TRAINER (TRAINER_ID);


-- query



-- 개체 등록
-- [등록]
INSERT INTO POKEMON 
(
    POKEMON_ID
    , NICKNAME
    , POKEMON_LEVEL
    , SPECIES_ID
    , TRAINER_ID
)
VALUES 
(
    SEQ_POKEMON.NEXTVAL
    , #{nickname}
    , #{pokemonLevel}
    , #{speciesId}
    , #{trainerId}
)
;

-- [조회 - 전체]
SELECT
    P.POKEMON_ID
    , P.NICKNAME
    , P.SPECIES_ID
    , P.POKEMON_LEVEL
    , S.NAME AS SPECIES_NAME
    , S.TYPE AS TYPE
    , P.TRAINER_ID
    , T.TRAINER_NAME
    , P.CAUGHT_AT
    , P.MODIFIED_AT
FROM POKEMON P
JOIN POKEMON_SPECIES S ON P.SPECIES_ID = S.SPECIES_ID
JOIN POKEMON_TRAINER T ON P.TRAINER_ID = T.TRAINER_ID
ORDER BY P.POKEMON_ID
;

-- [조회 - 단일]
SELECT 
    P.POKEMON_ID
    , P.NICKNAME
    , P.POKEMON_LEVEL
    , P.SPECIES_ID
    , S.NAME AS SPECIES_NAME
    , P.TRAINER_ID
    , T.TRAINER_NAME
    , P.CAUGHT_AT
    , P.MODIFIED_AT
FROM POKEMON P
JOIN POKEMON_SPECIES S ON P.SPECIES_ID = S.SPECIES_ID
JOIN POKEMON_TRAINER T ON P.TRAINER_ID = T.TRAINER_ID
WHERE P.POKEMON_ID = #{pokemonId}
;

-- [수정]
UPDATE POKEMON
SET 
    NICKNAME = '수정12'
    , POKEMON_LEVEL = 133
    , SPECIES_ID = 3
    , TRAINER_ID = 3
    , MODIFIED_AT = SYSDATE
WHERE POKEMON_ID = 1
;

-- [삭제]
UPDATE POKEMON
SET
    DEL_YN = 'N'
WHERE POKEMON_ID = #{pokemonId}
;




-- DUMMY DATA
-- 포켓몬 종 (POKEMON_SPECIES)
INSERT INTO POKEMON_SPECIES (SPECIES_ID, NAME, TYPE) VALUES (SEQ_POKEMON_SPECIES.NEXTVAL, '피카츄', '전기');
INSERT INTO POKEMON_SPECIES (SPECIES_ID, NAME, TYPE) VALUES (SEQ_POKEMON_SPECIES.NEXTVAL, '파이리', '불꽃');
INSERT INTO POKEMON_SPECIES (SPECIES_ID, NAME, TYPE) VALUES (SEQ_POKEMON_SPECIES.NEXTVAL, '꼬부기', '물');
INSERT INTO POKEMON_SPECIES (SPECIES_ID, NAME, TYPE) VALUES (SEQ_POKEMON_SPECIES.NEXTVAL, '이상해씨', '풀');
INSERT INTO POKEMON_SPECIES (SPECIES_ID, NAME, TYPE) VALUES (SEQ_POKEMON_SPECIES.NEXTVAL, '뮤츠', '에스퍼');

-- 트레이너 (POKEMON_TRAINER)
INSERT INTO POKEMON_TRAINER (TRAINER_ID, TRAINER_NAME) VALUES (SEQ_POKEMON_TRAINER.NEXTVAL, '고순');
INSERT INTO POKEMON_TRAINER (TRAINER_ID, TRAINER_NAME) VALUES (SEQ_POKEMON_TRAINER.NEXTVAL, '지우');
INSERT INTO POKEMON_TRAINER (TRAINER_ID, TRAINER_NAME) VALUES (SEQ_POKEMON_TRAINER.NEXTVAL, '이슬이');

-- 포켓몬 개체 (POKEMON)
INSERT INTO POKEMON (POKEMON_ID, NICKNAME, POKEMON_LEVEL, SPECIES_ID, TRAINER_ID, CAUGHT_AT)
VALUES (SEQ_POKEMON.NEXTVAL, '스파크', 12, 1, 1, SYSDATE);  -- 고순의 피카츄

INSERT INTO POKEMON (POKEMON_ID, NICKNAME, POKEMON_LEVEL, SPECIES_ID, TRAINER_ID, CAUGHT_AT)
VALUES (SEQ_POKEMON.NEXTVAL, '파오리', 7, 2, 2, SYSDATE-2);  -- 지우의 파이리

INSERT INTO POKEMON (POKEMON_ID, NICKNAME, POKEMON_LEVEL, SPECIES_ID, TRAINER_ID, CAUGHT_AT)
VALUES (SEQ_POKEMON.NEXTVAL, '마린', 5, 3, 3, SYSDATE-7);   -- 이슬이의 꼬부기

INSERT INTO POKEMON (POKEMON_ID, NICKNAME, POKEMON_LEVEL, SPECIES_ID, TRAINER_ID, CAUGHT_AT)
VALUES (SEQ_POKEMON.NEXTVAL, '씨앗', 8, 4, 1, SYSDATE-1);   -- 고순의 이상해씨

INSERT INTO POKEMON (POKEMON_ID, NICKNAME, POKEMON_LEVEL, SPECIES_ID, TRAINER_ID, CAUGHT_AT)
VALUES (SEQ_POKEMON.NEXTVAL, '엠투', 50, 5, 2, SYSDATE-15); -- 지우의 뮤츠