--======================================================
-- 20250724 과제
--======================================================

commit;

-- 테이블 Drop
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
-- 시퀀스 Drop
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_CATEGORY;

-- 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
--=====================================
-- 테이블 생성
-- 과제 01
CREATE TABLE BOARD 
(
    NO                  NUMBER              PRIMARY KEY
    , TITLE             VARCHAR2(100)
    , CONTENT           VARCHAR2(100)
    , CATEGORY_NO       NUMBER
    , CREATED_AT        DATE                DEFAULT SYSDATE
    , MODIFIED_AT       DATE
    , DEL_YN            CHAR(1)             DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
)
;
CREATE TABLE CATEGORY 
(
    CATEGORY_NO         NUMBER              PRIMARY KEY
    , CATEGORY_NAME     VARCHAR2(100)
   )
;

-- FK
ALTER TABLE BOARD
ADD CONSTRAINT FK_BOARD_CATEGORY
FOREIGN KEY (CATEGORY_NO)
REFERENCES CATEGORY (CATEGORY_NO);



































--==========================================================
-- 더미 데이터
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (SEQ_CATEGORY.NEXTVAL, 'JAVA');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (SEQ_CATEGORY.NEXTVAL, 'JS');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (SEQ_CATEGORY.NEXTVAL, 'CSS');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (SEQ_CATEGORY.NEXTVAL, 'HTML');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (SEQ_CATEGORY.NEXTVAL, 'SQL');

INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD.NEXTVAL, '테스트 게시글 1', '테스트 내용 1', 1);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD.NEXTVAL, '테스트 게시글 2', '테스트 내용 2', 1);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD.NEXTVAL, '테스트 게시글 3', '테스트 내용 3', 2);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD.NEXTVAL, '테스트 게시글 4', '테스트 내용 4', 2);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD.NEXTVAL, '테스트 게시글 5', '테스트 내용 5', 3);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD.NEXTVAL, '테스트 게시글 6', '테스트 내용 6', 3);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD.NEXTVAL, '테스트 게시글 7', '테스트 내용 7', 4);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD.NEXTVAL, '테스트 게시글 8', '테스트 내용 8', 5);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD.NEXTVAL, '테스트 게시글 9', '테스트 내용 9', 5);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD.NEXTVAL, '테스트 게시글 10', '테스트 내용 10', 5);



--==========================================================
-- 쿼리문 모음
-- INSERT
INSERT INTO BOARD
(
    NO
    , TITLE
    , CONTENT
    , CATEGORY_NO
)
VALUES 
(
    SEQ_BOARD.NEXTVAL
    , #{title}
    , #{content}
    , #{categoryNo}
)
;

-- SELECT LIST
SELECT
    B.NO
    , B.TITLE
    , B.CONTENT
    , C.CATEGORY_NAME
    , B.CREATED_AT 
    , B.MODIFIED_AT
    , B.DEL_YN
FROM BOARD B
JOIN CATEGORY C ON C.CATEGORY_NO = B.CATEGORY_NO
WHERE DEL_YN = 'N'
;


--  SELECT ONE BY NO
SELECT
    NO
    , TITLE
    , CONTENT
    , CREATED_AT 
    , MODIFIED_AT
    , DEL_YN
FROM BOARD
WHERE NO = #{no}
AND DEL_YN = 'N'
;

-- DELETE
UPDATE BOARD
    SET DEL_YN = 'Y'
WHERE POST_ID = #{no}
;

-- UPDATE
UPDATE BOARD
   SET
      TITLE = #{title}
    , CONTENT = #{content}
    , MODIFIED_AT = SYSDATE
WHERE NO = #{no}
AND DEL_YN = 'N'
;


